server:
  port: 80
spring:
  zipkin:
    base-url: http://192.168.56.10:9411
    sender:
      type: web
  cloud:
    gateway:
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
      globalcors:
        cors-configurations:
          '[/**]':  # 只要有人处理了请求，这个跨域就能生效
            allowed-origins:  #允许所有地址来源跨域
              - '*'
            allowed-methods: #允许所有请求方式
              - '*'
#              - GET
#              - POST
            allowed-headers: #允许所有请求头
              - '*'
            allowCredentials: true #允许带一些安全标志跨域 比如：Cookie
