server:
  port: 7000
spring:
  zipkin:
    base-url: http://192.168.56.10:9411
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3307/gmall_product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
