server:
  port: 7000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  zipkin:
    base-url: http://192.168.56.10:9411
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3307/gmall_product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456



app:
  minio:
    endpoint: http://192.168.56.10:9000
    ak: admin
    sk: admin123456
    bucket-name: gmall
  thread-pool:
    core: 4
    max: 8
